apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
  labels:
    app: my-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
        - name: my-web
          image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest 
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: /var/www/html
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: my-efs
