apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "41"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"my-web"},"name":"my-web","namespace":"idankatz-dev"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"my-web"}},"template":{"metadata":{"labels":{"app":"my-web"}},"spec":{"containers":[{"image":"image-registry.openshift-image-registry.svc:5000/idankatz-dev/konflux-lab:latest","imagePullPolicy":"Always","name":"parksmap","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"1G"},"requests":{"cpu":"100m","memory":"512Mi"}},"volumeMounts":[{"mountPath":"/mnt/data","name":"my-efs"}]},{"args":["-procall"],"image":"ncabatoff/process-exporter","name":"process-exporter","ports":[{"containerPort":9256,"protocol":"TCP"}]}],"shareProcessNamespace":true,"volumes":[{"name":"my-efs","persistentVolumeClaim":{"claimName":"my-efs"}}]}}}}
  generation: 110
  labels:
    app: my-web
  name: my-web
  namespace: idankatz-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/idankatz-dev/konflux-lab:latest
        imagePullPolicy: Always
        name: parksmap
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/data
          name: my-efs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: my-efs
        persistentVolumeClaim:
          claimName: my-efs
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2026-01-20T03:14:16Z"
    lastUpdateTime: "2026-01-20T09:58:38Z"
    message: ReplicaSet "my-web-8cf97755f" has successfully progressed.
    reason: NewReplicaSetAvailable
